var MSG_ONLY="只有"
var MSG_ARE_ALLOWED=" 被允许！"
var MSG_ALPHABETS="字母"
var MSG_NUMBERS="数字"
var MSG_SPACES="空格"
var MSG_CUSTOM_PATTERN="匹配模式的值"
var NO_CHAR_ALLOWED="不允许任何字符！"
var ENTER_VALUE_BETWEEN="请输入\"之间的值"
var FLOAT_RANGE='-9223372036854775808 和 9223372036854775807'
var INTEGER_RANGE='-9223372036854775808 和 9223372036854775807'
var ENTER_CORRECT_VALUE="请输入正确的值。"
var ENTER_CORRECT_VALUE_FOR="输入正确的值";
var PRECISION_VALUE="精度应在 0 到 ";
var CORRECT_VALUE="值不在范围内";
var FLOAT_LENGTH="最大长度可以是 15";
var INVALID_EMAIL="请输入有效的电子邮件 ID。"
var BATCH_MSG="您想保存当前数据吗？";
var INVALID_PHONE="请输入有效的电话号码。"
var MINMAXVALUEMSG="值应该在";
var MSG_AND=" 和 ";
var ONPASTE_MSG=" 字符可以粘贴到此字段中，因为它的字符限制为 ";
var ONLY_FIRST="只有第一个";
var YES="是";
var NO="否";
var SPACE_NOT_ALLOWED="粘贴时不允许有空格";
var NUMBER_NOT_ALLOWED="粘贴时不允许输入数字";
var ALPHABET_NOT_ALLOWED="粘贴时不允许使用字母";
var NOT_ALLOWED="粘贴时不允许";
var INVALID_SESSION="无效会话";
var SELECT="选择";
var AUTH_UNSUCCESSFUL="登录信息无效。";
var AUTH_UNSUCCESSFUL_TITLE="登录失败";
var BLANK_AUTH="请输入您的密码。"
var IS_NOT_ALLOWED="不允许";
var INVALID_POSITION="位置无效";
var CANNOT_USE="不能使用";
var MIN_VALUE_ERROR="控件的最小值为";
var MAX_VALUE_ERROR="控件的最大值为";
var SELECT_ALL="全选";
var NONE_SELECTED="未选择";
var SELECTED_TEXT="已选择";
var AUTH_INVALIDUSER="请输入邮箱ID";
var AUTH_INVALIDUSER_TITLE="登录失败";
var OPT_SEND_MSG="OTP 已发送至";
var OTP_EXPIRED="OTP 已过期。";
var OTP_EXPIRED_MSG="要在 <> 获取另一个 OTP，请按重新发送按钮";
var DIDNT_GET_OTP="没有得到 OTP？";
var SERVER_ERROR="服务器端发生错误，请检查服务器日志。";
var SERVER_ERROR_TITLE="服务器错误";
var LEFT="剩下";
var RIGHT="正确的";
var CAMERA_FILE_UPLOAD="文件上传成功";
var FRONT_CAMERA_ERROR="不支持前置摄像头模式，请旋转摄像头视图";
var BACK_CAMERA_ERROR="不支持后置摄像头模式，请旋转摄像头视图";
var CAMERA_IMAGE_ERROR="您的设备不支持相机";
var ACCESS_DENIED_LOCATION="用户拒绝地理定位请求。";
var LOCATION_UNAVILABLE="位置信息不可用。";
var TIME_OUT_LOCATION="获取用户位置的请求超时。";
var ERROR_OCCURRED="发生未知错误。";
var NAV_TITLE="导航错误";
var MANDATORY_TITLE="强制警报";
var DATA_TITLE="无效数据";
var SAVE_TITLE="保存失败";
var ERROR_TITLE="错误";
var SUCCESS_TITLE="成功";
var WORKITEM="工作项";
var CREATEMSG="创建成功";
var CREATE_TITLE="已创建工作项";
var MIN_WIDTH_ERROR="最小宽度应该小于最大宽度。";
var MAX_WIDTH_ERROR="最大宽度应该大于最小宽度。";
var MAX_FILE_SIZE_ERROR="最大文件大小只能为10MB";
var SLIDER_MAX="最大";
var SLIDER_MIN="分钟";
var SLIDER_VALUE="值";
var MAX_MIN_ERROR="最大值必须大于最小值";
var MIN_MAX_ERROR="min 必须小于 max";
var VALUE_MIN_ERROR="值必须大于或等于最小值";
var VALUE_MAX_ERROR="值必须小于或等于最大值";
var TILEALIGNLABEL="TileAlignLabel";
var SLIDER_UNIT="单位";
var DOC_ERROR="上传附件出错，请重试。";
var orientation_msg="此表单未针对横向模式进行优化。请将您的设备旋转到纵向模式以获得更好的体验";
var DEL_ERROR="无法删除预定义的属性";
var WIDTH_PX_LISTVIEW="现在将根据px计算列宽";
var NO_DATA_FOUND="未找到数据";
var SUBMIT_APPLICATION="您要提交申请吗？";
var CLOSE_WINDOW="请关闭窗口。";
var EXIST_APPLICATION="你有一个已经注册的应用程序。";
var SELECT_EXIST_APPLICATION="您要加载现有应用程序还是创建一个新应用程序？";
var LOGOUT_MSG="你想退出吗？";
var APP_SUB_SUCS="您的申请已提交。";
var DELETE_DOC_MSG="你确定要删除";
var CANCEL="取消";
var YES_REMOVE="是的，删除";
var TILE_SELECTION="要选择的瓷砖数量";
var SINGLE="单";
var MULTIPLE="多个";
var DEFAULT_TILE_SELECTION="要选择的默认图块";
var NONE="无";
var TILE_MAD_MSG="强制选择瓷砖";
var ERROR_TXT="错误文本";
var TILE_PLACEHOLDER="未选中图块时将显示此消息";
var FORM_SAVE_MSG="您的表单已保存。";
var OPEN_APPLICATION="打开现有应用程序";
var CREATE_NEW="新建";
var INFO="信息";
var DAY1="苏";
var DAY2="莫";
var DAY3="图";
var DAY4="我们";
var DAY5="Th";
var DAY6="Fr";
var DAY7="萨";
var MONTH1="一月";
var MONTH2="2 月";
var MONTH3="三月";
var MONTH4="四月";
var MONTH5="五月";
var MONTH6="六月";
var MONTH7="七月";
var MONTH8="8 月";
var MONTH9="Sep";
var MONTH10="十月";
var MONTH11="十一月";
var MONTH12="十二月";
var FULLMONTH1="一月";
var FULLMONTH2="二月";
var FULLMONTH3="三月";
var FULLMONTH4="四月";
var FULLMONTH5="五月";
var FULLMONTH6="六月";
var FULLMONTH7="七月";
var FULLMONTH8="八月";
var FULLMONTH9="九月";
var FULLMONTH10="十月";
var FULLMONTH11="十一月";
var FULLMONTH12="十二月";
var ERROR_MSG_INTERFACE="找不到支持的网络摄像头接口";
var DOC_COMMENT="写评论";
var TILE_MAX="不能输入超过最大值";
var TILE_MIN="不能输入小于分钟";
var THE_VALUE="价值";
var INCOMPATIBLE_MSG="不兼容";
var FIELD="字段";
var TABLE="桌子";
var ROW="排";
var COLUMN="列";
var OF="的";
var DELETE_Table_MSG="是否要删除该行？";
var DOCUMENT_NAME_MISSING="先输入文档名称";
var DUPLICATE_DOCUMENT_NAME="已设置文档名称";
var Doc_Comments_label="评论";
var Doc_Comments_Msg="请输入评论";
var SAVEEXITMSG="是否要保存并退出？";
var DELETE="删除";
var SHOW_LOGOUT_MSG="您已成功登出。";
var SPACE_NOT_ALLOWED_FOR="不允许有空格";
var NUMBER_NOT_ALLOWED_FOR="数字不允许用于";
var ALPHABET_NOT_ALLOWED_FOR="字母不允许用于 ";
var SEARCH="搜索";
var PDF_FILE_DOWNLOAD_SUCCESS="文件下载成功。"
var PDF_FILE_DOWNLOAD_FAILURE="文件下载失败。"
var PRE_VALIDATION_MSG_1="在网格中添加数据的问题-";
var PRE_VALIDATION_MSG_2=" ,请保存工作项并再次打开处理";
var INVALID_CHARACTERS="不允许使用字符 <、>、\"、(、)";